<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ScreenshotBox.Core/ScreenshotBox.Core.csproj" />
    <PackageReference Include="RapidOcrNet" Version="4.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../models/chinese/*" Link="models/chinese/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
